branches:
  only:
  - master

language: objective-c
osx_image: xcode8.1

script:
- xcodebuild -project BeeTee.xcodeproj -scheme "BeeTee OS X" build test
- xcodebuild -project BeeTee.xcodeproj -scheme "BeeTee iOS" -destination "platform=iOS Simulator,name=iPhone 7" build test

after_success:
- bash <(curl -s https://codecov.io/bash)  -J 'BeeTee'
